---
- hosts: all
  become: true
  vars:
    motd:
      - Ansible Managed Node by eysiiii, done on {{ inventory_hostname }}
  vars_prompt:
      - name: username
        prompt: Input your user name
        private: false
      - name: uid
        prompt: Input your own UID
        private: false

  tasks:
    - name: Install Python3 and Pip3
      package:
        name:
          - python3
          - python3-pip
        state: latest
        update_cache: yes

    - name: Set Python3 as the default
      alternatives:
        name: python
        path: /usr/bin/python3

    - name: Install java OpenJDK in ubuntu
      apt:
          name: openjdk-11-jdk 
          state: latest
          update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install java OpenJDK in ubuntu
      apt:
          name:
            - java-11-openjdk                                       
          state: latest 
          update_cache: yes
      when: ansible_distribution == "CentOS"


    - name: Set Pip3 as the default pip
      alternatives:
        name: pip
        path: /usr/bin/pip3

    - name: Create MOTD
      template:
        src: motd.j2
        dest: /etc/motd
      vars:
        motd_text: "{{ motd_text | default('Ansible Managed node by ' + ansible_user) }}"

    - name: Create User
      ansible.builtin.user:
        name- "{{ username }}"
        comment- NewUser
        uid- "{{ uid }}"
        createhome- yes
        home- /home/"{{ username }}"
        shell- /bin/bash
  
